import { Home, Contact, Shopping, Product, Products, Page404 } from 'pages';

export default [
  {
    path: '/',
    name: 'Home',
    component: Home,
    exact: true,
    strict: true,
    sensitive: false,
    showOnAppBar: true,
  },
  {
    path: '/contact',
    name: 'Contact',
    component: Contact,
    exact: true,
    strict: true,
    sensitive: false,
    showOnAppBar: true,
  },
  {
    path: '/shopping',
    name: 'Shopping',
    component: Shopping,
    exact: true,
    strict: true,
    sensitive: false,
    showOnAppBar: true,
  },
  {
    path: '/products',
    name: 'Products',
    component: Products,
    exact: true,
    strict: true,
    sensitive: false,
    showOnAppBar: true,
  },
  {
    path: '/product/:id',
    name: 'Product',
    component: Product,
    exact: true,
    strict: true,
    sensitive: false,
    showOnAppBar: false,
  },
  {
    // path: '',
    name: 'Page 404',
    component: Page404,
    // exact: true,
    // strict: true,
    // sensitive: false,
    showOnAppBar: false,
  },
];
